version: '3.8'

services:
  frontend:
    build:
      context: ./frontend_vue/hexegic
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - app-network
      
  backend:
    build:
      context: ./backend_connexion
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./backend_connexion/.env
    networks:
      - app-network
    volumes:
      - ./backend_connexion:/app
      
networks:
  app-network:
    driver: bridge